name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - junho

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      # 1. 권한 줄 때도 거실(pickmeal 폴더) 안으로 들어가서 하라고 지정합니다.
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        working-directory: ./pickmeal

      # 2. 빌드할 때도 거실 안에서 실행합니다.
      - name: Build with Gradle
        run: ./gradlew build
        working-directory: ./pickmeal

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: pickmeal
          environment_name: Pickmeal-env
          version_label: ${{ github.sha }}
          region: ap-northeast-2
          # 3. 배달할 물건(jar)도 거실 안의 창고(build/libs)에서 꺼내오라고 알려줍니다.
          deployment_package: pickmeal/build/libs/pickmeal-0.0.1-SNAPSHOT.jar